name:                 quote-quot
version:              0.2.1.0
visibility:           public
id:                   quote-quot-0.2.1.0-inplace
key:                  quote-quot-0.2.1.0-inplace
license:              BSD-3-Clause
copyright:            2020-2022 Andrew Lelechenko
maintainer:           andrew.lelechenko@gmail.com
author:               Andrew Lelechenko
homepage:             https://github.com/Bodigrim/quote-quot#readme
synopsis:             Divide without division
description:
    Generate routines for integer division, employing arithmetic
    and bitwise operations only, which are __2.5x-3.5x faster__
    than 'quot'. Divisors must be known in compile-time and be positive.

category:             Math, Numerical
abi:                  inplace
exposed:              True
exposed-modules:      Numeric.QuoteQuot
import-dirs:
    /home/runner/work/quote-quot/quote-quot/dist-newstyle/build/x86_64-linux/ghc-9.14.1/quote-quot-0.2.1.0/build

library-dirs:
    /home/runner/work/quote-quot/quote-quot/dist-newstyle/build/x86_64-linux/ghc-9.14.1/quote-quot-0.2.1.0/build

library-dirs-static:
    /home/runner/work/quote-quot/quote-quot/dist-newstyle/build/x86_64-linux/ghc-9.14.1/quote-quot-0.2.1.0/build

dynamic-library-dirs:
    /home/runner/work/quote-quot/quote-quot/dist-newstyle/build/x86_64-linux/ghc-9.14.1/quote-quot-0.2.1.0/build

data-dir:             /home/runner/work/quote-quot/quote-quot/.
hs-libraries:         HSquote-quot-0.2.1.0-inplace
depends:              base-4.22.0.0-fde1 template-haskell-2.24.0.0-7190
haddock-interfaces:
    /home/runner/work/quote-quot/quote-quot/dist-newstyle/build/x86_64-linux/ghc-9.14.1/quote-quot-0.2.1.0/doc/html/quote-quot/quote-quot.haddock

haddock-html:
    /home/runner/work/quote-quot/quote-quot/dist-newstyle/build/x86_64-linux/ghc-9.14.1/quote-quot-0.2.1.0/doc/html/quote-quot
